// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        return windows;
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyB6ElW8KAEf5rUgFqEX1V_CjEYY-U5YQqE',
    appId: '1:711692081196:web:afe14f6e13d31f191e5989',
    messagingSenderId: '711692081196',
    projectId: 'house-app-5f972',
    authDomain: 'house-app-5f972.firebaseapp.com',
    storageBucket: 'house-app-5f972.appspot.com',
    measurementId: 'G-L9NJRQ1SJJ',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyANlfKXoQYY4yKVVstziCyTlRrv30LDe8w',
    appId: '1:711692081196:android:62bff017d8beb6381e5989',
    messagingSenderId: '711692081196',
    projectId: 'house-app-5f972',
    storageBucket: 'house-app-5f972.appspot.com',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyBxt55HgicErQgBgdVSn8Hj-9h6TAy1wiE',
    appId: '1:711692081196:ios:0e2477113c1064091e5989',
    messagingSenderId: '711692081196',
    projectId: 'house-app-5f972',
    storageBucket: 'house-app-5f972.appspot.com',
    iosBundleId: 'com.example.house',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyBxt55HgicErQgBgdVSn8Hj-9h6TAy1wiE',
    appId: '1:711692081196:ios:0e2477113c1064091e5989',
    messagingSenderId: '711692081196',
    projectId: 'house-app-5f972',
    storageBucket: 'house-app-5f972.appspot.com',
    iosBundleId: 'com.example.house',
  );

  static const FirebaseOptions windows = FirebaseOptions(
    apiKey: 'AIzaSyB6ElW8KAEf5rUgFqEX1V_CjEYY-U5YQqE',
    appId: '1:711692081196:web:9e2fcb3bfa7b0cf11e5989',
    messagingSenderId: '711692081196',
    projectId: 'house-app-5f972',
    authDomain: 'house-app-5f972.firebaseapp.com',
    storageBucket: 'house-app-5f972.appspot.com',
    measurementId: 'G-9ZEPTN8DRJ',
  );
}
